name: dependency_install_workflow
on:
  push:
    branches:
      - main

jobs: 
  install_dependencies:
    name: Install Dependencies  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt


          