
name: First Workflow
on: workflow_dispatch 
jobs:
 basic: 
  runs-on: ubuntu-latest
  steps:
   - name: Print greeting
     run: |
          echo "Hello World!"
          echo "I told you so"
   - name: Print bye message
     run: echo "That's a bye!"

