name: Running workflows on multiple events
# controls when the workflow will run
on:
# here the event trigger is push
  #push:
    #branches:
      #- main
# workflow_dispatch is a feature to manually trigger the workflow
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

  # the schedule event allows you to run the workflow at specified times
  schedule:
    - cron: '2 * * * *'
jobs:
  my_job1: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4 

      - name: Run Job 1
        run: echo "this workflow is triggered on push, PR,schedule,or manual trigger this is a sample job for demo"
